import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://skyfunnel.ai/');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'Login' }).click();
  const page1 = await page1Promise;
  await page1.getByRole('textbox', { name: 'Enter your mail address' }).fill('demo@skyfunnel.ai');
  await page1.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page1.getByRole('textbox', { name: 'Password' }).fill('P');
  await page1.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page1.getByRole('textbox', { name: 'Password' }).fill('Pass#123');
  await page1.getByRole('button', { name: 'Login', exact: true }).click();
  await page1.getByRole('link', { name: 'WhatsApp', exact: true }).click();
  await page1.getByRole('link', { name: 'Template', exact: true }).click();
  await page1.getByRole('link', { name: '+ Create Template' }).click();
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page1.locator('div').filter({ hasText: /^Save$/ }).getByRole('textbox').fill('hiie');
  await page1.getByRole('button', { name: 'Save', exact: true }).click();
  await page1.getByRole('combobox').filter({ hasText: 'Select Template type' }).click();
  await page1.getByRole('option', { name: 'MARKETING' }).click();
  await page1.getByRole('combobox').filter({ hasText: 'Select Header type' }).click();
  await page1.getByRole('option', { name: 'Text' }).click();
  await page1.getByRole('textbox', { name: 'Header Text' }).fill('good evening');
  await page1.getByRole('textbox', { name: 'Body Text' }).fill('');
  await page1.getByRole('button', { name: 'B', exact: true }).click();
  await page1.getByRole('textbox', { name: 'Body Text' }).fill('hello everyone');
  await page1.getByRole('textbox', { name: 'Body Text' }).click();
  await page1.getByRole('textbox', { name: 'Body Text' }).fill('hello everyone*');
  await page1.getByRole('textbox', { name: 'Body Text' }).click();
  await page1.getByRole('textbox', { name: 'Body Text' }).fill('');
  await page1.getByRole('button', { name: 'S', exact: true }).click();
  await page1.getByRole('textbox', { name: 'Body Text' }).click();
  await page1.getByRole('textbox', { name: 'Body Text' }).fill('~_*hello everyone*_~');
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page1.getByRole('button', { name: 'grinning' }).click();
  await page1.getByRole('button', { name: 'Generate' }).click();
  await page1.locator('div').filter({ hasText: 'Take body content for' }).nth(3).click();
  await page1.getByRole('textbox', { name: 'Enter your prompt' }).fill('hello everyone,');
  await page1.getByRole('dialog').getByRole('button').nth(1).click();
  await page1.getByRole('textbox', { name: 'Footer Text' }).fill('byee');
  await page1.getByRole('button', { name: 'Add Marketing Opt-Out' }).click();
  await page1.getByRole('button', { name: 'Add URL Button' }).click();
  await page1.getByRole('button', { name: 'Add Phone Button' }).click();
  await page1.locator('div').filter({ hasText: /^URL Static$/ }).getByRole('button').click();
  await page1.getByRole('button', { name: 'Add Copy Code Button' }).click();
  await page1.getByRole('textbox', { name: 'Button text' }).first().click();
  await page1.getByRole('textbox', { name: 'Button text' }).nth(1).click();
  await page1.getByRole('textbox', { name: 'Button text' }).nth(1).fill('call');
  await page1.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page1.getByRole('textbox', { name: 'Enter phone number' }).fill('+91 ');
  await page1.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page1.getByRole('textbox', { name: 'Enter phone number' }).fill('+9174283 82757');
  await page1.getByRole('button', { name: 'Save Template' }).click();
  await page1.getByRole('button', { name: 'Save Template' }).click();
});